### PR TITLE
ensure memcached will be executed anyway

### PR DESCRIPTION
**Pull request by krystism**

### CODE REVIEW

**Comment by tianon** [comment]
I'm pretty -1 on this, especially in the context of the best practices: https://docs.docker.com/articles/dockerfile_best-practices/#entrypoint and https://docs.docker.com/articles/dockerfile_best-practices/#cmd

**Comment by md5** [comment]
I'm also not a fan of this, but don't something like what is done in `mysql` could make sense: https://github.com/semarj/mysql/blob/master/5.6/docker-entrypoint.sh#L8

For that image, passing a "command" starting with "-" will trigger the entrypoint to call `mysqld "$@"` instead of just `"$@"` (I know @tianon knows this since he wrote much of that entrypoint). That seems like a reasonable approach in general.

**Comment by tianon** [comment]
Yeah, I don't love that solution (since it doesn't work for things that need non-flag arguments too like `thrift` for example), but I think it's a good compromise.

**Comment by tianon** [comment]
Although adding an entrypoint script just for that seems like pretty serious overkill. :wink:

**Comment by md5** [comment]
Ah, right. There isn't an `ENTRYPOINT` currently... Totally agree.

**Comment by tianon** [comment]
Fixed by #3

**Pull request closed without merging**
