### PR TITLE
ubuntu support

### PR DESCRIPTION
**Pull request by olegabr**
The initial ubuntu support. copied from debian and adjusted with packages needed.

These links were used to find out which packages are needed:
https://launchpad.net/ubuntu/xenial/+source/memcached
http://packages.ubuntu.com/xenial/memcached
https://partner-images.canonical.com/core/xenial/current/ubuntu-xenial-core-cloudimg-amd64.manifest

### CODE REVIEW

**Comment by tianon** [comment]
Not sure how I feel about an official Ubuntu variant.  If we were to add this, why wouldn't we add other suite combinations too (which is a little insane for sure)? ie, what if anything makes "xenial" a special case versus "wheezy" or "trusty"? (especially given that the service itself works the same way regardless, AFAIK)

**Comment by olegabr** [comment]
Personally, I need it because ubuntu is our corporative politic. We need the infrastructure to be as secure as possible, that is why we want the same baseimage for all components used. It is not about ubuntu being better than anything else, we just can not have multiple baseimages with multiple security holes. It is easier to keep in touch with just one.
I've fixed the ubuntu to xenial for the same reason why you fixed the memcached version and not used just the `latest` link - for predictability. xenial is a LTS and when next LTS release will be out, we change the xenial to it in the Dockerfile.

**Comment by tianon** [comment]
Right, I understand exactly why you chose to use `:xenial` explicitly; that's straightforward.  My issue is that this "opens the floodgates", so to speak.  If we accept this variant, then soon we'll have a PR for an `ubuntu:trusty`-based image too.  Following that, we'll get a PR for a `fedora`-based variant.  Does that make more sense?

**Comment by olegabr** [comment]
Yes, I understand you. But why you think that it is bad? For me, as a docker user, it is always a trouble to find images of all required services with consistent baseimage choice. Some are based on debian:jessie, another on ubuntu:14, e.t.c. More baseimage variants is better for all docker community, I believe.
You, as a maintainer, may be want to limit number of variants to a minimum, it is completely understandable. I just think that docker community needs are supreme here. 
if more choices means too much headache for maintainers, it indicates some architecture or infrastructure problem, that should be addressed. Can you please elaborate here? What kind of difficulties you provision with more baseimage variants addition?

**Comment by olegabr** [comment]
Basically, there are two reasons I can see here:
1. Security. It is safer to have only one baseimage for all your docker services
2. Legacy services. We have an already working system on, say, ubuntu. Now we want to move the infrastructure to the docker. And what we see here? Literally every image uses it's own baseimage distro. It means that to move to docker, we need to adopt our configuration files and may be do some other unpredictable changes to the already working code. Take into account that we have no administering and security specialists in distributions other than, say, ubuntu. As a result, we have an additional entry threshold to the docker. My solution to this problem is equivalent support for different distros, but I'm open to other suggestions.

**Comment by yosifkit** [comment]
Unfortunately this is not something we want to support.  For most users, just running "memcached" at a specific version fulfills all their requirements.  They don't need to care about the underlying distribution it is running within.  If they are running their own application, in python for example, and they are unable to run it in our Debian or Alpine based python images, then they are free to install python and their required dependencies within CentOS or other base distribution image.

**Pull request closed without merging**
