### PR TITLE
Memcached alpine

### PR DESCRIPTION
**Pull request by ncopa**
add alpine variant of memcached.

### CODE REVIEW

**Comment by ncopa** [comment]
Not really sure if this was the correct way to add a variant

**Comment by tianon** [comment]
```diff
--- Dockerfile	2016-01-28 12:44:24.507261342 -0800
+++ /dev/fd/63	2016-01-29 11:25:22.969353863 -0800
@@ -1,30 +1,43 @@
-FROM debian:jessie
+FROM alpine:3.3
 
 # add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
-RUN groupadd -r memcache && useradd -r -g memcache memcache
-
-RUN apt-get update && apt-get install -y --no-install-recommends \
-		libevent-2.0-5 \
-	&& rm -rf /var/lib/apt/lists/*
+RUN adduser -D memcache
 
 ENV MEMCACHED_VERSION 1.4.25
 ENV MEMCACHED_SHA1 7fd0ba9283c61204f196638ecf2e9295688b2314
+ENV MEMCACHED_SHA256 f058437b3c224d321919a9a6bb4e3eedb2312ed718c0caf087ff2f04ab795dda
 
-RUN buildDeps='curl gcc libc6-dev libevent-dev make perl' \
-	&& set -x \
-	&& apt-get update && apt-get install -y $buildDeps --no-install-recommends \
-	&& rm -rf /var/lib/apt/lists/* \
+# https://github.com/memcached/memcached/issues/138
+RUN set -x \
+	&& apk add --no-cache --virtual .build-deps \
+		curl \
+		gcc \
+		libc-dev \
+		libevent-dev \
+		linux-headers \
+		make \
+		perl \
 	&& curl -SL "http://memcached.org/files/memcached-$MEMCACHED_VERSION.tar.gz" -o memcached.tar.gz \
 	&& echo "$MEMCACHED_SHA1  memcached.tar.gz" | sha1sum -c - \
-	&& mkdir -p /usr/src/memcached \
-	&& tar -xzf memcached.tar.gz -C /usr/src/memcached --strip-components=1 \
+	&& echo "$MEMCACHED_SHA256  memcached.tar.gz" | sha256sum -c - \
+	&& mkdir -p /usr/src \
+	&& tar -xzf memcached.tar.gz -C /usr/src \
 	&& rm memcached.tar.gz \
-	&& cd /usr/src/memcached \
+	&& cd /usr/src/memcached-$MEMCACHED_VERSION \
+	&& sed -i -e 's:#include <sys/signal.h>:#include <signal.h>:' *.c \
 	&& ./configure \
 	&& make \
 	&& make install \
-	&& cd / && rm -rf /usr/src/memcached \
-	&& apt-get purge -y --auto-remove $buildDeps
+	&& cd / && rm -rf /usr/src/memcached-* \
+	&& runDeps="$( \
+		scanelf --needed --nobanner --recursive /usr/local \
+			| awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
+			| sort -u \
+			| xargs -r apk info --installed \
+			| sort -u \
+	)" \
+	&& apk add --virtual .memcached-rundeps $runDeps \
+	&& apk del .build-deps
 
 COPY docker-entrypoint.sh /entrypoint.sh
 ENTRYPOINT ["/entrypoint.sh"]
```

**Comment by ncopa** [comment]
rebased against current master and did the following fixes:
- enable parallel builds
- fix travis config to use variant
- change the debian docker-entrypoint.sh to use posix shell for consistency
- fix generate-stackbrew-library

**Comment by jstarcher** [comment]
Can we merge this?

**Pull request closed without merging**
